# Generated by Django 3.0.9 on 2020-10-18 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0005_auto_20201014_1443'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
