# Generated by Django 3.0.9 on 2020-10-23 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0009_orderitem_total_cost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='total_cost',
        ),
    ]
