# Generated by Django 3.0.9 on 2020-10-23 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0010_remove_orderitem_total_cost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='quantity',
        ),
    ]
