# Generated by Django 3.0.9 on 2020-10-30 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0015_auto_20201030_1518'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
    ]
