# Generated by Django 3.0.9 on 2020-10-30 17:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0016_remove_order_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_number',
            field=models.CharField(default=django.utils.timezone.now, editable=False, max_length=32),
            preserve_default=False,
        ),
    ]
